#!/usr/bin/env Rscript

suppressMessages(library(tidyverse))
suppressMessages(library(extrafont))
suppressMessages(loadfonts())

stenotype_home <- "../.."
results_dir <- paste0(stenotype_home, "/results")
figures_dir <- paste0(results_dir, "/figures")

if (!file.exists(figures_dir)) {
  dir.create(figures_dir)
}

################################################################################
# Initialize theme
################################################################################

theme_set(
  theme_bw() +
    theme(text = element_text(family="Palatino", size=12),
          panel.grid.major = element_line(color="gray", linewidth=0.2),
          panel.grid.minor = element_line(color="gray", linewidth=0.2, linetype="dotted"),
          axis.ticks = element_line(linewidth=0.05),
          legend.margin = margin(0, 0, 0, 0),
          legend.position = "bottom",
          legend.key.size = unit(0.5, "cm"),
          legend.title = element_blank()))
brewer <- "Blues"

################################################################################
# Helper functions
################################################################################

save.graph <- function(plot, width=7.5, height=5) {
  file <- paste0(figures_dir, "/", substitute(plot))
  cat("Writing plot:", file, "\n")
  ggsave(file, plot=plot, width=width, height=height)
}

# Outputs a tibble in LaTeX format (minus the headers)
# Essentially just adds the & between columns and \\ at the end of each row
save.table <- function(table) {
  file <- paste0(figures_dir, "/", substitute(table))
  cat("Writing table:", file, "\n")
  cat("% DO NOT MODIFY: this file is generated by an R script\n", file=file)
  for (row in 1:nrow(table)) {
    for (col in 1:ncol(table)) {
      cat(table[[row, col]], file=file, append=TRUE)
      if (col < ncol(table)) cat(" & ", file=file, append=TRUE)
    }
    cat(" \\\\\n", file=file, append=TRUE)
  }
}

extract_pkg_file_cols <- function(tbl, pkg_n, pkg_tot, file_n, file_tot) {
  tbl %>%
    transmute(Dataset, Model,
              pkg.n=tbl[[pkg_n]], pkg.tot=tbl[[pkg_tot]],
              pkg.Percent=(pkg.n / pkg.tot) * 100,
              file.n=tbl[[file_n]], file.tot=tbl[[file_tot]],
              file.Percent=(file.n / file.tot) * 100) %>%
    mutate_at(c("pkg.n", "pkg.tot", "file.n", "file.tot"), as.integer)
}

extract_file_cols <- function(tbl, files, n, tot) {
  tbl %>%
    transmute(Dataset, Model,
              files=tbl[[files]],
              n=tbl[[n]],
              tot=tbl[[tot]],
              Percent=(n / tot) * 100) %>%
    mutate_at(c("files", "n", "tot"), as.integer)
}

format_numbers <- function(tbl) {
  tbl %>%
    mutate(across(where(is.double), scales::label_number(accuracy=0.1))) %>%
    mutate(across(where(is.integer), scales::label_comma()))
}

pivot_pkg_file <- function(tbl) {
  tbl <- tbl %>%
    pivot_longer(cols=-c(Dataset, Model),
                 names_to=c("scope", ".value"),
                 names_sep="\\.") %>%
    mutate(scope=case_when(str_equal(scope, "file") ~ "Files",
                           str_equal(scope, "pkg") ~ "Packages"))
  tbl$scope <- factor(tbl$scope, levels=c("Packages", "Files"))
  tbl
}

graph_pkg_file <- function(tbl) {
  tbl <- tbl %>%
    pivot_pkg_file() %>%
    mutate(Model=gsub("\\s", "\n", Model))
  tbl$Model <- factor(tbl$Model, levels=c("StarCoder-7B\nSingle",
                                          "StarCoder-7B\nMulti",
                                          "StenoType-7B\nMulti"))
  tbl$Dataset <- factor(tbl$Dataset, levels=c("TS-Sourced", "JS-Sourced"))
  tbl %>%
    ggplot(aes(x=Model, y=Percent, fill=Dataset)) +
      geom_bar(stat="identity", position=position_dodge()) +
      theme(axis.title.x=element_blank()) +
      scale_y_continuous(limits=c(0, 100),
                         breaks=seq(0, 100, by=20),
                        labels=scales::label_percent(scale=1)) +
      scale_fill_brewer(palette=brewer, direction=-1) +
      facet_grid(cols=vars(scope))
}

graph_file <- function(tbl) {
  tbl <- tbl %>%
    mutate(Model=gsub("\\s", "\n", Model))
  tbl$Model <- factor(tbl$Model, levels=c("StarCoder-7B\nSingle",
                                          "StarCoder-7B\nMulti",
                                          "StenoType-7B\nMulti"))
  tbl$Dataset <- factor(tbl$Dataset, levels=c("TS-Sourced", "JS-Sourced"))
  tbl %>%
    ggplot(aes(x=Model, y=Percent, fill=Dataset)) +
    geom_bar(stat="identity", position=position_dodge()) +
    theme(axis.title.x=element_blank()) +
    scale_y_continuous(limits=c(0, 100),
                       breaks=seq(0, 100, by=20),
                       labels=scales::label_percent(scale=1)) +
    scale_fill_brewer(palette=brewer, direction=-1)
}

################################################################################
# Read CSV and clean up data
################################################################################

summary_data <- read_csv(paste0(results_dir, "/", "summary.csv"),
                         show_col_types=FALSE)

# Split out and rename the dataset
summary_data <- summary_data %>%
  separate_wider_regex(model, c(model = ".*", "_", dataset="ts|js")) %>%
  mutate(dataset=case_when(str_equal(dataset, "ts") ~ "TS-Sourced",
                           str_equal(dataset, "js") ~ "JS-Sourced")) %>%
  rename(Dataset = dataset)

# Rename models
summary_data <- summary_data %>%
  mutate(model=case_when(str_equal(model, "starcoderbase-7b_approach1") ~ "StarCoder-7B Single",
                         str_equal(model, "starcoderbase-7b_approach4") ~ "StarCoder-7B Multi",
                         str_starts(model, "stenotype") ~ "StenoType-7B Multi",
                         .default = model)) %>%
  rename(Model = model)

# Move Dataset to first column and sort
summary_data <- summary_data %>% relocate(Dataset)

################################################################################
# Package and files that parse
################################################################################

parses_data <- summary_data %>%
  extract_pkg_file_cols("tot_pkg_parses",
                        "tot_completions",
                        "tot_files_parse",
                        "tot_files")

parses.tex <- parses_data %>%
  format_numbers()

save.table(parses.tex)

parses.pdf <- parses_data %>%
  graph_pkg_file()

save.graph(parses.pdf)

################################################################################
# Package and files that type check
################################################################################

typechecks_data <- summary_data %>%
  extract_pkg_file_cols("tot_type_checks",
                        "tot_completions",
                        "tot_errorfree_files",
                        "tot_files")

typechecks.tex <- typechecks_data %>%
  format_numbers()

save.table(typechecks.tex)

typechecks.pdf <- typechecks_data %>%
  graph_pkg_file()

save.graph(typechecks.pdf)

################################################################################
# Trivial type annotations (per file)
################################################################################

trivial_annotations_data <- summary_data %>%
  extract_file_cols("tot_errorfree_files",
                    "tot_annotations_trivial_errorfree_files",
                    "tot_annotations_added_errorfree_files")

trivial_annotations.tex <- trivial_annotations_data %>%
  format_numbers()

save.table(trivial_annotations.tex)

trivial_annotations.pdf <- trivial_annotations_data %>%
  graph_file()

save.graph(trivial_annotations.pdf)

################################################################################
# Filled annotation sites (per file)
################################################################################

filled_annotations_data <- summary_data %>%
  extract_file_cols("tot_files_parse",
                    "tot_annotations_added_files_parse",
                    "tot_annotation_sites_files_parse")

filled_annotations.tex <- filled_annotations_data %>%
  format_numbers()

save.table(filled_annotations.tex)

filled_annotations.pdf <- filled_annotations_data %>%
  graph_file()

save.graph(filled_annotations.pdf)

################################################################################
# Type definitions added (per file)
################################################################################

type_defs_added_data <- summary_data %>%
  extract_file_cols("tot_files_parse",
                    "tot_definitions_added_files_parse",
                    "tot_definitions_files_parse")

type_defs_added.tex <- type_defs_added_data %>%
  format_numbers()

save.table(type_defs_added.tex)

type_defs_added.pdf <- type_defs_added_data %>%
  graph_file()

save.graph(type_defs_added.pdf)

################################################################################
# Type definitions used (per file)
################################################################################

type_defs_used_data <- summary_data %>%
  extract_file_cols("tot_files_parse",
                    "tot_definitions_used_files_parse",
                    "tot_definitions_files_parse")

type_defs_used.tex <- type_defs_used_data %>%
  format_numbers()

save.table(type_defs_used.tex)

type_defs_used.pdf <- type_defs_used_data %>%
  graph_file()

save.graph(type_defs_used.pdf)

################################################################################
# Package and files that were unchanged
################################################################################

unchanged_data <- summary_data %>%
  extract_pkg_file_cols("tot_pkg_unchanged",
                        "tot_completions",
                        "tot_files_unchanged",
                        "tot_files")

unchanged.tex <- unchanged_data %>%
  format_numbers()

save.table(unchanged.tex)

unchanged.pdf <- unchanged_data %>%
  graph_pkg_file()

save.graph(unchanged.pdf)

################################################################################
# Correct migrations
################################################################################

correct_data <- summary_data %>%
  extract_file_cols("tot_completions",
                    "tot_correct",
                    "tot_files") %>%
  select(-files)

correct.tex <- correct_data %>%
  format_numbers()

save.table(correct.tex)

correct.pdf <- correct_data %>%
  graph_file()

save.graph(correct.pdf)
